services:
  apt-cacher-ng:
    restart: always
    image: ghcr.io/jeffwcollins/apt-cacher-ng
    init: true
    ports:
      - "3142:3142"
    volumes:
      - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng